name: Bindings

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Bindings Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show Rust version
        run: rustc --version

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            bindings/target
          key: rust-${{ runner.os }}-${{ hashFiles('bindings/Cargo.toml') }}
          restore-keys: rust-

      - name: Check bindings formatting
        run: just bindings-fmt-check

      - name: Build bindings
        run: just bindings-build

      - name: Lint bindings
        run: just bindings-lint
