name: Bindings

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Bindings Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show Rust version
        run: rustc --version

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: bindings

      - name: Check bindings formatting
        run: just bindings-fmt-check

      - name: Build bindings
        run: just bindings-build

      - name: Lint bindings
        run: just bindings-lint
