name: Contracts

on:
  push:
    branches: [main, next]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Contracts Tests
    runs-on: macos-latest
    env:
      FOUNDRY_PROFILE: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Foundry version
        run: forge --version

      - name: Show Soldeer version
        run: forge soldeer version

      - name: Install dependencies
        run: just contracts-deps

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Show Bun version
        run: bun --version

      - name: Install the contract tooling
        run: just contracts-tooling

      - name: Lint contracts
        run: just contracts-lint

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Show Slither version
        run: slither --version

      - name: Run Slither Static Analyzer
        run: just contracts-static-analysis

      - name: Run Forge fmt
        run: just contracts-fmt-check

      - name: Check that bindings are up-to-date
        run: just bindings-check
